"""tax rule packs

Revision ID: 976fb219497d
Revises: 314401107ce6
Create Date: 2026-08-06 04:36:50.199438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976fb219497d'
down_revision: Union[str, Sequence[str], None] = '314401107ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rule_packs',
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('grant_type', sa.String(), nullable=False),
    sa.Column('effective_start_date', sa.Date(), nullable=False),
    sa.Column('calculation_method', sa.String(), nullable=False),
    sa.Column('official_source_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pack_id'),
    sa.UniqueConstraint('country_code', 'grant_type', 'effective_start_date', name='uq_tax_rule_packs_country_type_date')
    )
    with op.batch_alter_table('tax_rule_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_rule_packs_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rule_packs_grant_type'), ['grant_type'], unique=False)

    with op.batch_alter_table('income_tax_brackets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pack_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_income_tax_brackets_country_type_date_order', ['country_code', 'grant_type', 'effective_start_date', 'bracket_order'])
        batch_op.create_foreign_key('fk_income_tax_brackets_pack_id', 'tax_rule_packs', ['pack_id'], ['pack_id'])

    with op.batch_alter_table('tax_rates_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pack_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_tax_rates_history_country_type_date', ['country_code', 'grant_type', 'effective_start_date'])
        batch_op.create_foreign_key('fk_tax_rates_history_pack_id', 'tax_rule_packs', ['pack_id'], ['pack_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_rates_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tax_rates_history_pack_id', type_='foreignkey')
        batch_op.drop_constraint('uq_tax_rates_history_country_type_date', type_='unique')
        batch_op.drop_column('pack_id')

    with op.batch_alter_table('income_tax_brackets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_income_tax_brackets_pack_id', type_='foreignkey')
        batch_op.drop_constraint('uq_income_tax_brackets_country_type_date_order', type_='unique')
        batch_op.drop_column('pack_id')

    with op.batch_alter_table('tax_rule_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_rule_packs_grant_type'))
        batch_op.drop_index(batch_op.f('ix_tax_rule_packs_country_code'))

    op.drop_table('tax_rule_packs')
    # ### end Alembic commands ###
