"""notification center user state

Revision ID: 11434b49810c
Revises: eca19ffceb4d
Create Date: 2026-07-29 06:27:33.673186

Notification Center (v0.5.0) - שתי טבלאות מצב-משתמש בלבד.

ההתראות עצמן מחושבות בכל קריאה מ-DeterministicESOPEngine ולא נשמרות, ולכן אין כאן
טבלת notifications. נשמר רק מה שהמנוע לא יכול לגזור מהנתונים: מה המשתמש ביקש לקבל
(notification_preferences) ומה הוא כבר סגר (notification_dismissals).

downgrade מוחק את שתי הטבלאות במלואן. זה מוחק העדפות ו-dismissals של משתמשים, אבל
לא נוגע בשום נתון עסקי (מענקים/הבשלה/בקשות) - במקרה הגרוע ההתראות שנסגרו יחזרו להופיע.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11434b49810c'
down_revision: Union[str, Sequence[str], None] = 'eca19ffceb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_dismissals',
    sa.Column('dismissal_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('notification_key', sa.String(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dismissal_id')
    )
    with op.batch_alter_table('notification_dismissals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_dismissals_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notification_dismissals_user_key', ['user_id', 'notification_key'], unique=True)

    op.create_table('notification_preferences',
    sa.Column('preference_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('preference_id'),
    sa.UniqueConstraint('user_id', 'rule', name='uq_notification_preferences_user_rule')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))

    op.drop_table('notification_preferences')
    with op.batch_alter_table('notification_dismissals', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_dismissals_user_key')
        batch_op.drop_index(batch_op.f('ix_notification_dismissals_user_id'))

    op.drop_table('notification_dismissals')
    # ### end Alembic commands ###
