"""unique constraint on tax rates history pack id

Revision ID: 4ccffff30b94
Revises: 976fb219497d
Create Date: 2026-08-06 09:59:29.152564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ccffff30b94'
down_revision: Union[str, Sequence[str], None] = '976fb219497d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_rates_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tax_rates_history_pack_id', ['pack_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_rates_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tax_rates_history_pack_id', type_='unique')

    # ### end Alembic commands ###
