"""baseline schema

Revision ID: eca19ffceb4d
Revises:
Create Date: 2026-07-28 05:03:27.084592

baseline של הסכמה כפי שהיא ב-models.py בגרסה 0.4.0. נוצר ב-autogenerate מול DB ריק,
כך ש-DB חדש לגמרי נבנה במלואו ב-alembic upgrade head.

*** אזהרה: על esop_database.db הקיים אסור להריץ upgrade ***
הוא כבר מכיל את כל 13 הטבלאות (נבנו ב-create_all), ולכן upgrade ייפול על
"table companies already exists". הפעולה החד-פעמית הנכונה שם היא alembic stamp head,
שרק רושם את מספר הרוויזיה בלי להריץ DDL. ראה את ה-runbook ב-README.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca19ffceb4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('income_tax_brackets',
    sa.Column('bracket_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('grant_type', sa.String(), nullable=False),
    sa.Column('effective_start_date', sa.Date(), nullable=False),
    sa.Column('bracket_order', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('official_source_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bracket_id')
    )
    with op.batch_alter_table('income_tax_brackets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_tax_brackets_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_tax_brackets_effective_start_date'), ['effective_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_tax_brackets_grant_type'), ['grant_type'], unique=False)

    op.create_table('tax_rates_history',
    sa.Column('tax_rule_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('grant_type', sa.String(), nullable=False),
    sa.Column('effective_start_date', sa.Date(), nullable=False),
    sa.Column('capital_gains_rate', sa.Float(), nullable=False),
    sa.Column('official_source_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tax_rule_id')
    )
    with op.batch_alter_table('tax_rates_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_rates_history_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rates_history_grant_type'), ['grant_type'], unique=False)

    op.create_table('employees',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TERMINATED', 'ON_LEAVE', 'DECEASED', name='employeestatus'), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_company_id'), ['company_id'], unique=False)

    op.create_table('option_pools',
    sa.Column('pool_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('total_shares', sa.Float(), nullable=False),
    sa.Column('allocated_shares', sa.Float(), nullable=False),
    sa.Column('unallocated_shares', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('allocated_shares + unallocated_shares = total_shares', name='ck_option_pools_shares_balance'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('pool_id')
    )
    with op.batch_alter_table('option_pools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_option_pools_company_id'), ['company_id'], unique=False)

    op.create_table('stock_prices_history',
    sa.Column('price_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('fmv_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    with op.batch_alter_table('stock_prices_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_prices_history_company_id'), ['company_id'], unique=False)

    op.create_table('trustees',
    sa.Column('trustee_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('trustee_id')
    )
    with op.batch_alter_table('trustees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trustees_company_id'), ['company_id'], unique=False)

    op.create_table('grants',
    sa.Column('grant_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('pool_id', sa.String(), nullable=False),
    sa.Column('trustee_id', sa.String(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=False),
    sa.Column('grant_type', sa.Enum('IL_102_CAPITAL_GAINS', 'IL_102_WORK_INCOME', 'US_ISO', 'US_NSO', name='granttype'), nullable=False),
    sa.Column('total_options', sa.Float(), nullable=False),
    sa.Column('exercise_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('trustee_deposit_date', sa.Date(), nullable=True),
    sa.Column('post_termination_window_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['option_pools.pool_id'], ),
    sa.ForeignKeyConstraint(['trustee_id'], ['trustees.trustee_id'], ),
    sa.PrimaryKeyConstraint('grant_id')
    )
    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grants_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grants_pool_id'), ['pool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grants_trustee_id'), ['trustee_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('password_salt', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('COMPANY_ADMIN', 'TRUSTEE', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('trustee_id', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['trustee_id'], ['trustees.trustee_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('before_value', sa.String(), nullable=True),
    sa.Column('after_value', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('exercise_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('grant_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('options_requested', sa.Float(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='exerciserequeststatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.grant_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('exercise_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_requests_grant_id'), ['grant_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('vesting_schedules',
    sa.Column('schedule_id', sa.String(), nullable=False),
    sa.Column('grant_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('cliff_months', sa.Integer(), nullable=True),
    sa.Column('total_months', sa.Integer(), nullable=True),
    sa.Column('paused_days_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.grant_id'], ),
    sa.PrimaryKeyConstraint('schedule_id'),
    sa.UniqueConstraint('grant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vesting_schedules')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('exercise_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_requests_grant_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_requests_employee_id'))

    op.drop_table('exercise_requests')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grants_trustee_id'))
        batch_op.drop_index(batch_op.f('ix_grants_pool_id'))
        batch_op.drop_index(batch_op.f('ix_grants_employee_id'))

    op.drop_table('grants')
    with op.batch_alter_table('trustees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trustees_company_id'))

    op.drop_table('trustees')
    with op.batch_alter_table('stock_prices_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_prices_history_company_id'))

    op.drop_table('stock_prices_history')
    with op.batch_alter_table('option_pools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_pools_company_id'))

    op.drop_table('option_pools')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_company_id'))

    op.drop_table('employees')
    with op.batch_alter_table('tax_rates_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_rates_history_grant_type'))
        batch_op.drop_index(batch_op.f('ix_tax_rates_history_country_code'))

    op.drop_table('tax_rates_history')
    with op.batch_alter_table('income_tax_brackets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_tax_brackets_grant_type'))
        batch_op.drop_index(batch_op.f('ix_income_tax_brackets_effective_start_date'))
        batch_op.drop_index(batch_op.f('ix_income_tax_brackets_country_code'))

    op.drop_table('income_tax_brackets')
    op.drop_table('companies')
    # ### end Alembic commands ###
