"""event ledger and ownership index

Revision ID: 314401107ce6
Revises: 2e62bb1fbb96
Create Date: 2026-08-05 16:26:00.595693

v0.6.0 שלב 1: שתי טבלאות חדשות בלבד - ``ledger_events`` (הרצף הבלתי-ניתן-לעריכה
שממנו נגזר מצב עסקי) ו-``ledger_ownership`` (אינדקס בעלות נפרד לצורך הרשאות,
לעולם לא נגזר מאירועים משוחזרים). שתי הטבלאות ריקות ב-upgrade הזה - החיווט
לחמש נקודות המוטציה הקיימות קורה בשלב 3, והגיבוי (backfill_ledger.py) רץ
בנפרד אחרי המיגרציה, לא כחלק ממנה.

*** אין כאן את בעיית ה-NOT NULL/server_default או ה-batch_alter_table-מול-FK
שנתקלנו בהן ב-v0.5.1 *** - שתי אלה היו ALTER TABLE על טבלה קיימת עם שורות
ו-FK-ים נכנסים מטבלאות אחרות. כאן מדובר ב-CREATE TABLE טרי: אין שורות קיימות
שדורשות server_default, ואף טבלה עדיין לא מצביעה *לתוך* ledger_events (ה-FK
העצמי corrects_event_id הוא היחיד, ואינו נבדק ב-INSERT הראשון כי הוא nullable).
עדיין נבדק בפועל מול עותק של esop_database.db (55 משתמשים, 260 עובדים,
250 מענקים) לפני שנסמכים על ההנחה הזו - ראו למטה.

הטריגרים בסוף upgrade() הם הגנת השינוי (tamper-evidence) שהוחלט עליה בתכנון:
UPDATE/DELETE על ledger_events נדחים ברמת ה-DB. לא hash-chaining/הצפנה - זה
over-engineering ביחס לאיום האמיתי כאן (ראו FEATURE_SPEC.md v0.6.0).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '314401107ce6'
down_revision: Union[str, Sequence[str], None] = '2e62bb1fbb96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_ownership',
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('trustee_id', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['trustee_id'], ['trustees.trustee_id'], ),
    sa.PrimaryKeyConstraint('aggregate_id')
    )
    with op.batch_alter_table('ledger_ownership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_ownership_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_ownership_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_ownership_trustee_id'), ['trustee_id'], unique=False)

    op.create_table('ledger_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('corrects_event_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['corrects_event_id'], ['ledger_events.event_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('aggregate_id', 'sequence_no', name='uq_ledger_events_aggregate_seq')
    )
    with op.batch_alter_table('ledger_events', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_events_aggregate', ['aggregate_type', 'aggregate_id'], unique=False)
        batch_op.create_index('ix_ledger_events_effective_date', ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_ledger_events_recorded_at', ['recorded_at'], unique=False)

    # הגנת שינוי: append-only נאכף ברמת ה-DB, לא רק במוסכמה של קוד האפליקציה.
    op.execute("""
        CREATE TRIGGER trg_ledger_events_no_update BEFORE UPDATE ON ledger_events
        BEGIN SELECT RAISE(ABORT, 'ledger_events is append-only: UPDATE is rejected'); END;
    """)
    op.execute("""
        CREATE TRIGGER trg_ledger_events_no_delete BEFORE DELETE ON ledger_events
        BEGIN SELECT RAISE(ABORT, 'ledger_events is append-only: DELETE is rejected'); END;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # הטריגרים חייבים לרדת לפני drop_table - SQLite לא מוחק אותם אוטומטית
    # מספיק מהר בתוך אותה טרנזקציה של batch recreate.
    op.execute("DROP TRIGGER IF EXISTS trg_ledger_events_no_update")
    op.execute("DROP TRIGGER IF EXISTS trg_ledger_events_no_delete")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_events', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_events_recorded_at')
        batch_op.drop_index(batch_op.f('ix_ledger_events_event_type'))
        batch_op.drop_index('ix_ledger_events_effective_date')
        batch_op.drop_index('ix_ledger_events_aggregate')

    op.drop_table('ledger_events')
    with op.batch_alter_table('ledger_ownership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_ownership_trustee_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_ownership_employee_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_ownership_company_id'))

    op.drop_table('ledger_ownership')
    # ### end Alembic commands ###
