"""documents and national id

Revision ID: 56baedac6e53
Revises: 4ccffff30b94
Create Date: 2026-08-06 11:31:03.937259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56baedac6e53'
down_revision: Union[str, Sequence[str], None] = '4ccffff30b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('template_type', sa.String(), nullable=False),
    sa.Column('grant_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('trustee_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACKNOWLEDGED', 'DECLINED', 'EXPIRED', name='documentstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_sha256', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.grant_id'], ),
    sa.ForeignKeyConstraint(['trustee_id'], ['trustees.trustee_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_grant_id'), ['grant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_trustee_id'), ['trustee_id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # תוקן ידנית: documents.employee_id הוא FK נכנס ל-employees. batch_alter_table
    # על employees (שמאחוריו drop+recreate ב-SQLite) נכשל ב-FOREIGN KEY constraint
    # failed כל עוד documents עדיין קיימת - בדיוק אותו דפוס שכבר נתפס ב-v0.6.0.
    # documents (והאינדקסים שלה) חייבת להיעלם ראשונה.
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_trustee_id'))
        batch_op.drop_index(batch_op.f('ix_documents_grant_id'))
        batch_op.drop_index(batch_op.f('ix_documents_employee_id'))
        batch_op.drop_index(batch_op.f('ix_documents_company_id'))

    op.drop_table('documents')

    # employees.national_id דורש drop אמיתי של עמודה - SQLite עושה את זה ע"י
    # יצירת טבלה חדשה + מחיקת הישנה, וזה נכשל עם FK constraint כל עוד טבלאות
    # אחרות (Grant/User/ExerciseRequest/LedgerOwnership) מפנות אל employees
    # ו-migrations/env.py מדליק PRAGMA foreign_keys=ON על כל חיבור. זו הפעם
    # הראשונה בפרויקט שמורידים עמודה מ-employees - כל שינוי קודם רק הוסיף
    # עמודות (ADD COLUMN טבעי ב-SQLite, לא דורש recreate). לכן מכבים את
    # אכיפת ה-FK רק סביב הפעולה הזו, לא גלובלית.
    op.execute("PRAGMA foreign_keys=OFF")
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('national_id')
    op.execute("PRAGMA foreign_keys=ON")
    # ### end Alembic commands ###
